DROP TABLE IF EXISTS account CASCADE;
create table account
(
    id bigint generated by default as identity,
    balance bigint,
    number varchar(255),
    primary key (id)
);

DROP TABLE IF EXISTS customer CASCADE;
create table customer
(
    id bigint generated by default as identity,
    name varchar(255),
    email_address varchar(255),
    phone_number varchar(255),
    primary key (id)
);

DROP TABLE IF EXISTS accounts CASCADE;
create table accounts
(
    customer_id bigint not null,
    account_id bigint not null
);

alter table accounts add constraint FKimhipb2c1ymh3ryyxywbwocr6 foreign key (account_id) references account;
alter table accounts add constraint FKrsongaercg5ag17nbv2v877us foreign key (customer_id) references customer;

INSERT INTO account (balance, number) VALUES (5000, '1234-1234');
INSERT INTO account (balance, number) VALUES (10, '1234-5678');
INSERT INTO account (balance, number) VALUES (123123, '9876-9876');

INSERT INTO customer (name, email_address, phone_number) VALUES ('Biro Janos', 'biro@janos.hu', '70 123-4567');
INSERT INTO customer (name, email_address, phone_number) VALUES ('Zemen Zsolt', 'zemen@zsolt.hu', '20 123-4567');
INSERT INTO customer (name, email_address, phone_number) VALUES ('Kanyasi Eszter', 'kanyasi@eszter.hu', '30 123-4567');

INSERT INTO accounts (customer_id, account_id) VALUES (1, 1);
INSERT INTO accounts (customer_id, account_id) VALUES (2, 2);
INSERT INTO accounts (customer_id, account_id) VALUES (3, 3);
