DROP TABLE IF EXISTS account CASCADE;
create table account
(
    id bigint generated by default as identity,
    balance bigint,
    number varchar(255),
    primary key (id)
);

DROP TABLE IF EXISTS customer CASCADE;
create table customer
(
    id bigint generated by default as identity,
    name varchar(255),
    email_address varchar(255),
    phone_number varchar(255),
    primary key (id)
);

DROP TABLE IF EXISTS accounts CASCADE;
create table accounts
(
    customer_id bigint not null,
    account_id bigint not null
);

alter table accounts add constraint FKimhipb2c1ymh3ryyxywbwocr6 foreign key (account_id) references account;
alter table accounts add constraint FKrsongaercg5ag17nbv2v877us foreign key (customer_id) references customer;